export const ON_UPLOAD = 'ON_UPLOAD'
export const OFF_UPLOAD = 'OFF_UPLOAD'
export const SET_ITEMS = 'SET_ITEMS'
export const REMOVE_ITEMS = 'REMOVE_ITEMS'
export const REMOVE_ITEM_BY_ERROR = 'REMOVE_ITEM_BY_ERROR'
