export const FETCH_INVOICE_SELLER = 'FETCH_INVOICE_SELLER'
export const SET_XAUTH = 'SET_XAUTH'
export const CHANGE_LOGIN_STATE = 'CHANGE_LOGIN_STATE'
export const SIGN_OUT = 'SIGN_OUT'
export const SET_AXIOS_HEADER = 'SET_AXIOS_HEADER'
export const SET_USER_COOKIES = 'SET_USER_COOKIES'

// user info
export const SET_USER_INFO = 'SET_USER_INFO'
export const CHANGE_USER_NAME = 'CHANGE_USER_NAME'
export const CHANGE_USER_PROFILE = 'CHANGE_USER_PROFILE'
export const DELETE_USER_INFO = 'DELETE_USER_INFO'
export const CHANGE_USER_COUNTRY = 'CHANGE_USER_COUNTRY'
export const CHANGE_USER_TIMEZONE = 'CHANGE_USER_TIMEZONE'

// popup
export const POPUP_OPEN = 'POPUP_OPEN'
export const POPUP_CLOSE = 'POPUP_CLOSE'
