// mypage
export const CHANGE_FULL_NAME = 'CHANGE_FULL_NAME'
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD'
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR'
export const RESEND_EMAIL = 'RESEND_EMAIL'
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_BILLING_ADDRESS = 'CHANGE_BILLING_ADDRESS'
export const ALERT_PROFILE_UPLOAD_FAIL = 'ALERT_PROFILE_UPLOAD_FAIL'
export const INVOICE = 'INVOICE'
export const CHANGE_CARD = 'CHANGE_CARD'
export const CHANGE_CARD_ERROR = 'CHANGE_CARD_ERROR'
export const CANCEL_SUBSCRIPTION = 'CANCEL_SUBSCRIPTION'
export const CANCEL_SUBSCRIPTION_SUCCESS = 'CANCEL_SUBSCRIPTION_SUCCESS'
export const CHANGE_COUNTRY = 'CHANGE_COUNTRY'
export const CHANGE_TIMEZONE = 'CHANGE_TIMEZONE'


// price
export const ALERT_SAME_PLAN = 'ALERT_SAME_PLAN'
export const ALERT_HAS_LICENSE = 'ALERT_HAS_LICENSE'
export const ALERT_REMAIN_SUB = 'ALERT_REMAIN_SUB'
export const ALERT_ATELIER_GUIDE = 'ALERT_ATELIER_GUIDE'
export const CHECKOUT_FAIL = 'CHECKOUT_FAIL'
export const PROMOTION_LOGIN = 'PROMOTION_LOGIN'

// trial
export const ALERT_TRIAL_HAS_LICENSE = 'ALERT_TRIAL_HAS_LICENSE'
export const ALERT_TRIAL_EXPIRED = 'ALERT_TRIAL_EXPIRED'
export const ALERT_TRIAL_LOGIN = 'ALERT_TRIAL_LOGIN'

// users
export const SOCIAL_CONTENT = 'SOCIAL_CONTENT'
export const USER_STORY = 'USER_STORY'

// contact us
export const ALERT_ATTACHFILE_UPLOAD_FAIL = 'ALERT_ATTACHFILE_UPLOAD_FAIL'

// join
export const TOOLTIP_STUDENT = 'TOOLTIP_STUDENT'
export const TOOLTIP_STUDENT_JOIN = 'TOOLTIP_STUDENT_JOIN'

// mobile
export const MOBILE_BUY = 'MOBILE_BUY'

// 이용약관
export const TERMS = 'TEMRS'
export const TERMS_SERVICE = 'service'
export const TERMS_PRIVACY = 'privacy'

export const OBT_ENTERPRISE = 'OBT_ENTERPRISE'

// etc
export const VIEW_LARGE_IMAGE = 'VIEW_LARGE_IMAGE'